-- CreateEnum
CREATE TYPE "AppointmentCancellationReason" AS ENUM ('PATIENT_REQUEST', 'PATIENT_ILLNESS', 'PATIENT_EMERGENCY', 'DOCTOR_UNAVAILABLE', 'CLINIC_REQUEST', 'SCHEDULING_CONFLICT', 'TRANSPORTATION_ISSUE', 'DUPLICATE_BOOKING', 'RESCHEDULED_ELSEWHERE', 'OTHER');

-- CreateEnum
CREATE TYPE "AppointmentNoShowReason" AS ENUM ('FORGOT_APPOINTMENT', 'UNREACHABLE', 'TRANSPORTATION_ISSUE', 'PATIENT_EMERGENCY', 'SCHEDULING_MISUNDERSTANDING', 'NO_CONFIRMATION', 'OTHER', 'UNKNOWN');

-- AlterTable
ALTER TABLE "appointments"
ADD COLUMN "cancellationReason" "AppointmentCancellationReason",
ADD COLUMN "cancellationNote" TEXT,
ADD COLUMN "noShowReason" "AppointmentNoShowReason",
ADD COLUMN "noShowNote" TEXT;
